export const locations = {
  'AC': { 'Rio Branco': ['Centro', 'Bosque'] },
  'AL': { 'Maceió': ['Ponta Verde', 'Jatiúca'] },
  'AP': { 'Macapá': ['Central', 'Santa Rita'] },
  'AM': { 'Manaus': ['Adrianópolis', 'Ponta Negra'] },
  'BA': { 'Salvador': ['Barra', 'Pituba', 'Rio Vermelho'] },
  'CE': { 'Fortaleza': ['Meireles', 'Aldeota'] },
  'DF': { 'Brasília': ['Asa Sul', 'Asa Norte', 'Lago Sul'] },
  'ES': { 'Vitória': ['Jardim Camburi', 'Praia do Canto'] },
  'GO': { 'Goiânia': ['Setor Marista', 'Bueno'] },
  'MA': { 'São Luís': ['Ponta D\'Areia', 'Calhau'] },
  'MT': { 'Cuiabá': ['Centro-Norte', 'Santa Rosa'] },
  'MS': { 'Campo Grande': ['Centro', 'Jardim dos Estados'] },
  'MG': { 'Belo Horizonte': ['Savassi', 'Lourdes', 'Funcionários'] },
  'PA': { 'Belém': ['Nazaré', 'Umarizal'] },
  'PB': { 'João Pessoa': ['Manaíra', 'Tambaú'] },
  'PR': { 'Curitiba': ['Batel', 'Centro Cívico'] },
  'PE': { 'Recife': ['Boa Viagem', 'Pina'] },
  'PI': { 'Teresina': ['Centro', 'Fátima'] },
  'RJ': { 'Rio de Janeiro': ['Copacabana', 'Ipanema', 'Leblon', 'Barra da Tijuca'], 'Niterói': ['Icaraí', 'Centro'] },
  'RN': { 'Natal': ['Ponta Negra', 'Petrópolis'] },
  'RO': { 'Porto Velho': ['Centro', 'Flodoaldo Pontes Pinto'] },
  'RR': { 'Boa Vista': ['Centro', 'Paraviana'] },
  'RS': { 'Porto Alegre': ['Moinhos de Vento', 'Bela Vista'] },
  'SC': { 'Florianópolis': ['Jurerê Internacional', 'Lagoa da Conceição'] },
  'SP': { 'São Paulo': ['Jardins', 'Moema', 'Pinheiros', 'Vila Olímpia', 'Morumbi'], 'Campinas': ['Centro', 'Cambuí', 'Nova Campinas'] },
  'SE': { 'Aracaju': ['Jardins', 'Atalaia'] },
  'TO': { 'Palmas': ['Plano Diretor Sul', 'Graciosa'] },
};